import { ethers, run } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("Starting deployment to Sepolia testnet...\n");

  const [deployer] = await ethers.getSigners();
  const balance = await ethers.provider.getBalance(deployer.address);

  console.log("Deploying with account:", deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "ETH");

  if (balance < ethers.parseEther("0.01")) {
    console.error("\nInsufficient balance. Need at least 0.01 Sepolia ETH.");
    console.error("Get testnet ETH from: https://cloud.google.com/application/web3/faucet/ethereum/sepolia");
    process.exit(1);
  }

  console.log("\n--- Deploying contracts ---\n");

  const CommunityToken = await ethers.getContractFactory("CommunityToken");
  const token = await CommunityToken.deploy("Bosques Community Token", "BOSQUES", 18, 1000000, deployer.address);
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();
  console.log("CommunityToken:", tokenAddress);

  const ProjectRegistry = await ethers.getContractFactory("ProjectRegistry");
  const registry = await ProjectRegistry.deploy();
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log("ProjectRegistry:", registryAddress);

  const EscrowVault = await ethers.getContractFactory("EscrowVault");
  const escrow = await EscrowVault.deploy(tokenAddress);
  await escrow.waitForDeployment();
  const escrowAddress = await escrow.getAddress();
  console.log("EscrowVault:", escrowAddress);

  const MilestoneManager = await ethers.getContractFactory("MilestoneManager");
  const milestones = await MilestoneManager.deploy();
  await milestones.waitForDeployment();
  const milestonesAddress = await milestones.getAddress();
  console.log("MilestoneManager:", milestonesAddress);

  const Governance = await ethers.getContractFactory("Governance");
  const governance = await Governance.deploy(tokenAddress);
  await governance.waitForDeployment();
  const governanceAddress = await governance.getAddress();
  console.log("Governance:", governanceAddress);

  const Reporting = await ethers.getContractFactory("Reporting");
  const reporting = await Reporting.deploy();
  await reporting.waitForDeployment();
  const reportingAddress = await reporting.getAddress();
  console.log("Reporting:", reportingAddress);

  // Write .env.sepolia with deployed addresses
  const envPath = path.join(__dirname, "../../.env.sepolia");
  const envContent = [
    "# Sepolia contract addresses — auto-generated by deploy-sepolia.ts",
    `COMMUNITY_TOKEN_ADDRESS=${tokenAddress}`,
    `PROJECT_REGISTRY_ADDRESS=${registryAddress}`,
    `ESCROW_VAULT_ADDRESS=${escrowAddress}`,
    `MILESTONE_MANAGER_ADDRESS=${milestonesAddress}`,
    `GOVERNANCE_ADDRESS=${governanceAddress}`,
    `REPORTING_ADDRESS=${reportingAddress}`,
    `DEPLOYER_ADDRESS=${deployer.address}`,
    `CHAIN_ID=11155111`,
    `VITE_CHAIN_ID=11155111`,
    `VITE_RPC_URL=https://eth-sepolia.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY || "YOUR_KEY"}`,
  ].join("\n") + "\n";

  fs.writeFileSync(envPath, envContent);
  console.log("\nAddresses written to .env.sepolia");

  // Verify contracts on Etherscan (skip if no API key)
  if (process.env.ETHERSCAN_API_KEY) {
    console.log("\nVerifying contracts on Etherscan (waiting 30s for indexing)...");
    await new Promise((r) => setTimeout(r, 30000));
    try {
      await run("verify:verify", { address: tokenAddress, constructorArguments: ["Bosques Community Token", "BOSQUES", 18, 1000000, deployer.address] });
      await run("verify:verify", { address: registryAddress, constructorArguments: [] });
      await run("verify:verify", { address: escrowAddress, constructorArguments: [tokenAddress] });
      await run("verify:verify", { address: milestonesAddress, constructorArguments: [] });
      await run("verify:verify", { address: governanceAddress, constructorArguments: [tokenAddress] });
      await run("verify:verify", { address: reportingAddress, constructorArguments: [] });
      console.log("All contracts verified on Etherscan.");
    } catch (e) {
      console.warn("Etherscan verification failed (non-fatal):", (e as Error).message);
    }
  }

  console.log("\n=== DEPLOYMENT COMPLETE ===");
  console.log("Network: Sepolia (chain 11155111)");
  console.log("CommunityToken:   ", tokenAddress);
  console.log("ProjectRegistry:  ", registryAddress);
  console.log("EscrowVault:      ", escrowAddress);
  console.log("MilestoneManager: ", milestonesAddress);
  console.log("Governance:       ", governanceAddress);
  console.log("Reporting:        ", reportingAddress);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
