import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("🚀 Starting deployment to local network...\n");

  const [deployer, validator1, validator2, planner, investor] = await ethers.getSigners();

  console.log("Deploying contracts with account:", deployer.address);
  console.log("Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH\n");

  // Deploy CommunityToken
  console.log("📝 Deploying CommunityToken...");
  const CommunityToken = await ethers.getContractFactory("CommunityToken");
  const token = await CommunityToken.deploy(
    "Bosques Community Token",
    "BOSQUES",
    18,
    1000000, // 1M initial supply
    deployer.address
  );
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();
  console.log("✅ CommunityToken deployed to:", tokenAddress);

  // Deploy ProjectRegistry
  console.log("\n📝 Deploying ProjectRegistry...");
  const ProjectRegistry = await ethers.getContractFactory("ProjectRegistry");
  const registry = await ProjectRegistry.deploy();
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log("✅ ProjectRegistry deployed to:", registryAddress);

  // Deploy EscrowVault
  console.log("\n📝 Deploying EscrowVault...");
  const EscrowVault = await ethers.getContractFactory("EscrowVault");
  const escrow = await EscrowVault.deploy(tokenAddress);
  await escrow.waitForDeployment();
  const escrowAddress = await escrow.getAddress();
  console.log("✅ EscrowVault deployed to:", escrowAddress);

  // Deploy MilestoneManager
  console.log("\n📝 Deploying MilestoneManager...");
  const MilestoneManager = await ethers.getContractFactory("MilestoneManager");
  const milestones = await MilestoneManager.deploy();
  await milestones.waitForDeployment();
  const milestonesAddress = await milestones.getAddress();
  console.log("✅ MilestoneManager deployed to:", milestonesAddress);

  // Deploy Governance
  console.log("\n📝 Deploying Governance...");
  const Governance = await ethers.getContractFactory("Governance");
  const governance = await Governance.deploy(tokenAddress);
  await governance.waitForDeployment();
  const governanceAddress = await governance.getAddress();
  console.log("✅ Governance deployed to:", governanceAddress);

  // Deploy Reporting
  console.log("\n📝 Deploying Reporting...");
  const Reporting = await ethers.getContractFactory("Reporting");
  const reporting = await Reporting.deploy();
  await reporting.waitForDeployment();
  const reportingAddress = await reporting.getAddress();
  console.log("✅ Reporting deployed to:", reportingAddress);

  // Grant roles
  console.log("\n🔐 Setting up roles...");

  // Grant VALIDATOR_ROLE
  const VALIDATOR_ROLE = ethers.keccak256(ethers.toUtf8Bytes("VALIDATOR_ROLE"));
  await registry.grantRole(VALIDATOR_ROLE, validator1.address);
  await registry.grantRole(VALIDATOR_ROLE, validator2.address);
  await escrow.grantRole(VALIDATOR_ROLE, validator1.address);
  await escrow.grantRole(VALIDATOR_ROLE, validator2.address);
  await milestones.grantRole(VALIDATOR_ROLE, validator1.address);
  await milestones.grantRole(VALIDATOR_ROLE, validator2.address);
  console.log("✅ Granted VALIDATOR_ROLE to:", validator1.address, validator2.address);

  // Grant PLANNER_ROLE
  const PLANNER_ROLE = ethers.keccak256(ethers.toUtf8Bytes("PLANNER_ROLE"));
  await registry.grantRole(PLANNER_ROLE, planner.address);
  await milestones.grantRole(PLANNER_ROLE, planner.address);
  console.log("✅ Granted PLANNER_ROLE to:", planner.address);

  // Grant REPORTER_ROLE
  const REPORTER_ROLE = ethers.keccak256(ethers.toUtf8Bytes("REPORTER_ROLE"));
  await reporting.grantRole(REPORTER_ROLE, deployer.address);
  console.log("✅ Granted REPORTER_ROLE to:", deployer.address);

  // Grant escrow and milestones admin access to registry
  const DEFAULT_ADMIN_ROLE = ethers.ZeroHash;
  await registry.grantRole(DEFAULT_ADMIN_ROLE, escrowAddress);
  await milestones.grantRole(DEFAULT_ADMIN_ROLE, escrowAddress);
  console.log("✅ Granted admin access to contracts");

  // Distribute test tokens
  console.log("\n💰 Distributing test tokens...");
  const amount = ethers.parseEther("10000");
  await token.transfer(validator1.address, amount);
  await token.transfer(validator2.address, amount);
  await token.transfer(planner.address, amount);
  await token.transfer(investor.address, amount);
  console.log("✅ Distributed 10,000 BOSQUES to each test account");

  // Write addresses to .env.local
  console.log("\n📄 Writing addresses to .env.local...");
  const envPath = path.join(__dirname, "../../.env.local");
  const envContent = `
# Contract Addresses (Auto-generated by deploy-local.ts)
COMMUNITY_TOKEN_ADDRESS=${tokenAddress}
PROJECT_REGISTRY_ADDRESS=${registryAddress}
ESCROW_VAULT_ADDRESS=${escrowAddress}
MILESTONE_MANAGER_ADDRESS=${milestonesAddress}
GOVERNANCE_ADDRESS=${governanceAddress}
REPORTING_ADDRESS=${reportingAddress}

# Test Accounts
DEPLOYER_ADDRESS=${deployer.address}
VALIDATOR1_ADDRESS=${validator1.address}
VALIDATOR2_ADDRESS=${validator2.address}
PLANNER_ADDRESS=${planner.address}
INVESTOR_ADDRESS=${investor.address}
`;

  fs.writeFileSync(envPath, envContent);
  console.log("✅ Addresses written to .env.local");

  // Summary
  console.log("\n" + "=".repeat(60));
  console.log("🎉 DEPLOYMENT COMPLETE!");
  console.log("=".repeat(60));
  console.log("\nContract Addresses:");
  console.log("  CommunityToken:    ", tokenAddress);
  console.log("  ProjectRegistry:   ", registryAddress);
  console.log("  EscrowVault:       ", escrowAddress);
  console.log("  MilestoneManager:  ", milestonesAddress);
  console.log("  Governance:        ", governanceAddress);
  console.log("  Reporting:         ", reportingAddress);
  console.log("\nTest Accounts:");
  console.log("  Deployer:          ", deployer.address);
  console.log("  Validator 1:       ", validator1.address);
  console.log("  Validator 2:       ", validator2.address);
  console.log("  Planner:           ", planner.address);
  console.log("  Investor:          ", investor.address);
  console.log("\n✅ All accounts funded with 10,000 BOSQUES tokens");
  console.log("\n📝 Next steps:");
  console.log("  1. Run 'yarn seed' to populate database");
  console.log("  2. Run 'yarn start:dev' to start backend and frontend");
  console.log("=".repeat(60) + "\n");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
